service: glasswall-core-mass-tester-l


provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-west-2

#package:
#  exclude:
#    - lib/**
#  include:
#    - include-me.py
#    - include-me-dir/**

layers:
  lib:
    path: lib
    name: gw-core-rebuild-eval
    description: "layer for Glasswall Engine"

functions:
  test-manager:
    handler: manager.main
    iamRoleStatements:
      - Effect: "Allow"
        Action: "lambda:InvokeFunction"
        Resource: "*"
    events:
      - http:
          path: manager/run
          method: post
  test-runner:
    handler: runner.main
    layers:
      - {Ref: LibLambdaLayer}

resources: # CloudFormation template syntax from here on.
  Resources:
    ProcessingRecordsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProcessingRecordsTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-plugin-layer-manager
  - serverless-iam-roles-per-function

custom:
  serverless-offline:
    useDocker: true