service: glasswall-core-mass-tester-l


provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-west-2

package:
  include:
    - lib/**
  exclude:
    - test/**

#layers:
#  lib:
#    path: lib
#    name: gw-core-rebuild-eval
#    description: "layer for Glasswall Engine"

functions:
  test-manager:
    handler: manager.main
    iamRoleStatements:
      - Effect: "Allow"
        Action: "lambda:InvokeFunction"
        Resource: "*"
    events:
      - http:
          path: manager/run
          method: post
  test-runner:
    handler: runner.main
#    layers:
#      - {Ref: LibLambdaLayer}

resources: # CloudFormation template syntax from here on.
  Resources:
    ProcessRecordsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProcessRecordsTable
        AttributeDefinitions:
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: timestamp
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-plugin-layer-manager
  - serverless-iam-roles-per-function

custom:
  serverless-offline:
    useDocker: true